### ISSUE TITLE
Failure with flake8 3.0.4

### ISSUE THREAD

**Issue by JeanFred** [cogniteev/flake8-unicode-string-literal#1]
With flake8 3.0.4, the installation works but any flake8 execution crashes with:

```
Traceback (most recent call last):
  File "/usr/local/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/usr/local/lib/python2.7/dist-packages/flake8/main/application.py", line 316, in run
    self._run(argv)
  File "/usr/local/lib/python2.7/dist-packages/flake8/main/application.py", line 299, in _run
    self.initialize(argv)
  File "/usr/local/lib/python2.7/dist-packages/flake8/main/application.py", line 290, in initialize
    self.register_plugin_options()
  File "/usr/local/lib/python2.7/dist-packages/flake8/main/application.py", line 150, in register_plugin_options
    self.check_plugins.register_options(self.option_manager)
  File "/usr/local/lib/python2.7/dist-packages/flake8/plugins/manager.py", line 481, in register_options
    list(self.manager.map(register_and_enable))
  File "/usr/local/lib/python2.7/dist-packages/flake8/plugins/manager.py", line 277, in map
    yield func(self.plugins[name], *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flake8/plugins/manager.py", line 477, in register_and_enable
    call_register_options(plugin)
  File "/usr/local/lib/python2.7/dist-packages/flake8/plugins/manager.py", line 373, in generated_function
    return method(optmanager, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flake8/plugins/manager.py", line 223, in register_options
    add_options(optmanager)
  File "/usr/local/lib/python2.7/dist-packages/unicode_string_literal.py", line 25, in add_options
    parser.config_options.append('utter-unicode-string-literals')
AttributeError: 'OptionManager' object has no attribute 'config_options'
```

This is working fine with flake8 2.6.2
