### PR TITLE
Migrate to flake8 3.x

### LINKED ISSUE #1: Failure with flake8 3.0.4
With flake8 3.0.4, the installation works but any flake8 execution crashes with:

```
Traceback (most recent call last):
  File "/usr/local/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/usr/local/lib/python2.7/dist-packages/flake8/main/application.py", line 316, in run
    self._run(argv)
  File "/usr/local/lib/python2.7/dist-packages/flake8/main/application.py", line 299, in _run
    self.initialize(argv)
  File "/usr/local/lib/python2.7/dist-packages/flake8/main/application.py", line 290, in initialize
    self.register_plugin_options()
  File "/usr/local/lib/python2.7/dist-packages/flake8/main/application.py", line 150, in register_plugin_options
    self.check_plugins.register_options(self.option_manager)
  File "/usr/local/lib/python2.7/dist-packages/flake8/plugins/manager.py", line 481, in register_options
    list(self.manager.map(register_and_enable))
  File "/usr/local/lib/python2.7/dist-packages/flake8/plugins/manager.py", line 277, in map
    yield func(self.plugins[name], *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flake8/plugins/manager.py", line 477, in register_and_enable
    call_register_options(plugin)
  File "/usr/local/lib/python2.7/dist-packages/flake8/plugins/manager.py", line 373, in generated_function
    return method(optmanager, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flake8/plugins/manager.py", line 223, in register_options
    add_options(optmanager)
  File "/usr/local/lib/python2.7/dist-packages/unicode_string_literal.py", line 25, in add_options
    parser.config_options.append('utter-unicode-string-literals')
AttributeError: 'OptionManager' object has no attribute 'config_options'
```

This is working fine with flake8 2.6.2

### PR DESCRIPTION
**Pull request by JeanFred**
Since flake8 3.0, registering options is handled differently.

See http://flake8.pycqa.org/en/latest/plugin-development/cross-compatibility.html

Fix #1

### CODE REVIEW

**Comment by JeanFred** [comment]
This means that this plugin will not be compatible anymore with flake8 2.x. If that’s a concern, the docs indicate we can use `flake8-polyfill` but not sure the extra-dependency and the extra glue is worth it :)

**Comment by alexntt** [comment]
Any chance of merging this? flake8 is now at 3.2.1 and while this plugin would be very useful to us, pinning flake8<3 is not ideal.
